### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by dalenoe** [akshatmittal/youtube-realtime#1]
How hard would it be to make this work for a channel, instead of the user.

**Comment by akshatmittal** [comment]
Channel IDs are pretty long and random, while usernames are shorter and memorable. That's the main reason to choose usernames over channel IDs.

I'm trying to get it work with vanity URLs, but YouTube does not provide an API to query that, so I'm stuck there.

**Comment by dalenoe** [comment]
That's true. I was just wondering, as I was looking for something like this to work with the channels.

**Comment by akshatmittal** [comment]
I just can not find anything to do it this way, still keeping this issue open. Anybody is welcome to submit a pull request or explain something here if they have a solution. :)

**Comment by dalenoe** [comment]
@akshatmittal I am going to mess with it a little, but I did come up with this.

Here is a link to pull some channel data..

https://www.googleapis.com/youtube/v3/channels?part=statistics&id=UCkWnH9JZyNXe0t2k6GMN2aQ&key=API-KEY-GOES-HERE

**Comment by dalenoe** [comment]
Another reason using a channel, is because some user's have several channels.

**Comment by akshatmittal** [comment]
Yes, I'm aware on how to use the channel ID. But nobody wants to enter that long channel ID string. It's better to just use username or vanity URL. I'm searching for something to use the vanity URL.

**Comment by akshatmittal** [comment]
Hey @dalenoe, I just got some time away from my college stuff so I updated the project to support channels, for the least. :)

Examples: 
- https://akshatmittal.github.io/youtube-realtime/#!/UCKlhpmbHGxBE6uw9B_uLeqQ
- https://akshatmittal.github.io/youtube-realtime/#!/UC-lHJZR3Gqxm24_Vd_AJ5Yw

**Comment by dalenoe** [comment]
Awesome. I will have to check it out! Thanks.. :+1:

**Comment by petertenhoor** [comment]
Nice that channel ID's work now!

Do you by any chance see the possibility to also make your counter work with a YouTube channel name instead of of the channel username?

Example: A youtuber has the channelname 'FCroelie'. When I enter this URL in the browser it opens his channel: youtube.com/fcroelie. It does work to enter his channel ID in your tool, but when I enter 'FCRoelie' it does not return any values.

Greetings,

Peter
