### ISSUE TITLE
JS Files and jQuery

### ISSUE THREAD

**Issue by ghost** [akshatmittal/youtube-realtime#11]
I noticed that you have one long javascript file. This can get out of hand when new features are added and I suggest it to be split in separate files.

Also, I suggest using jQuery because this would shrink down your code significantly.

**Comment by akshatmittal** [comment]
I will not be using jQuery for this particular project. Even though it'll shrink down my code, the included overhead is far more significant.

As of splitting the files, I guess that's not a practice I'd like to follow. Plus, this does not give me any performance gain (but actually reduces it) and the file ain't "too" long anyways.

Your views are welcome! :)
