### ISSUE TITLE
0 Subs???

### ISSUE THREAD

**Issue by alchzh** [akshatmittal/youtube-realtime#12]
![wtf](http://i.imgur.com/onO9bOs.png)  
What is going on?

EDIT: Seems like there is no Sub count displayed [on Youtube](https://www.youtube.com/channel/UCvl0tqpDv9OTGBuqmeNVjrw/about). However, there is a view count.

**Comment by akshatmittal** [comment]
This is because the Subscriber Count is hidden in YouTube preferences.
