### ISSUE TITLE
Redirected to your site

### ISSUE THREAD

**Issue by Legoman99573** [akshatmittal/youtube-realtime#14]
Is it suppose to do this or will i need to change something?

**Comment by isaizamora** [comment]
that speaks friend

**Comment by akshatmittal** [comment]
The first few lines in the Javascript for the project forces this behavior to make some invalid pages to redirect back, and this includes forks as well. Just remove that particular part of code and you should be fine.

**Comment by somosdigitalmentegsm** [comment]
Hello how are you, all the files are on my website but when you put the code or name of a YouTube channel nothing happens, why? Should I place some Youtube API? Facebook ? tell me please I would like that to work on my website well
