### ISSUE TITLE
redirect to your website

### ISSUE THREAD

**Issue by TelefoonVandaag** [akshatmittal/youtube-realtime#19]
Hello,

Your index.html automatically redirects to your website?
How can I solve this..?

Thanks :D!

**Comment by akshatmittal** [comment]
Check #14.

**Comment by kurtzawn** [comment]
Your index.html automatically redirects to your website?
How can I solve this..?

Im already change URI my website in base.js and what next?

**Comment by kurtzawn** [comment]
could you please tell us, which js should be disable? which line ?
