### ISSUE TITLE
Help with odometer

### ISSUE THREAD

**Issue by BillyJohnsonn** [akshatmittal/youtube-realtime#2]
So, we have tried this open source. But everytime we start it up... The main Odometer does not work and is just set to 2,500,500. We have tried multiple ways of fixing it, but none of them worked. So I was wondering if you can help us out?

**Comment by akshatmittal** [comment]
When the Odometer shows 2,500,500, it means there was some problem retrieving the data. Check your javascript file for the correct API key and also make sure that the username you have entered is valid.

**Comment by BillyJohnsonn** [comment]
Alright. Thanks! One more thing, is it possible to change the "#!" to "?!"? If it is, how?
Example: http://akshatmittal.github.io/youtube-realtime/#!/PewDiePie
from that, to this: http://akshatmittal.github.io/youtube-realtime/?!/PewDiePie

**Comment by akshatmittal** [comment]
It is certainly possible, check out the code in [script.js from line 99](https://github.com/akshatmittal/youtube-realtime/blob/gh-pages/script.js#L99) till the end.

Using the hash is a better choice since the browser already knows that the page doesn't need to be reloaded. Using a "?!" in the URL would need one to write code for the same, plus search engines would take the pages as "Duplicates" which is bad.

**Comment by BillyJohnsonn** [comment]
Well I did change them already. The one that said "#!/" and just "!/". I changed them to "#username=". and "username=". But the thing is, when I change the "#" to a question mark, the page keeps refreshing itself. It is flipping out. Is that what you meant by really bad? Turning it into a "?" would help us with the Google Analytics.That is why we need it if you were wondering.

**Comment by akshatmittal** [comment]
That's exactly the issue. You need to prevent the page from reloading by overriding the default behaviour of the browser using JS. `e.preventDefault()` would be useful with the event. 

As for Google Analytics, you don't really need to do that. You can just use Google Analytics Custom Events to send the precise information about what username was checked out.

**Comment by BillyJohnsonn** [comment]
Alright. I am about to try out the e.preventDefault(). Is it literally just "e.preventDefault()" or do I have to add on? Also, where would be the best place to inupt it?

**Comment by akshatmittal** [comment]
You need to write a bunch of code which overrides the default browser behaviour. `e.preventDefault()` would be used with the unload event.

**Comment by BillyJohnsonn** [comment]
Hmm. Alright. Well I have one more question. Can you help me out on making it so a certain page(Person) has a different background and text color than the others?
So for instance, this URL: http://akshatmittal.github.io/youtube-realtime/#!/PewDiePie has a Red background while all of the others are just white.

**Comment by akshatmittal** [comment]
You just need to add a filter in the username change function, that should be easy enough.

**Comment by BillyJohnsonn** [comment]
Alright. I have never done either of those before, so if you have some of time on your hands do you think you can help us out with them?

**Comment by akshatmittal** [comment]
I've pushed a new Git Commit. This now shows the username in Google Analytics. The code for changing the background for specific people is simple enough, but it's not something I'd like to add to this open-source project. 

Maybe, just email me once and I'll help you out. :)

Email: hi@akshatmittal.com

**Comment by BillyJohnsonn** [comment]
Alright. Thanks for the help so far. Email coming your way :P
