### ISSUE TITLE
The embedding code doesn't display on mobile devices

### ISSUE THREAD

**Issue by haellon** [akshatmittal/youtube-realtime#21]
Hi,
great application by the way. loving it on my site. but when it comes to mobiles. the iframe won't display in mobile devices below 352px. please check on it. good work Akshat...

**Comment by akshatmittal** [comment]
Hey, that really shouldn't happen. The widget forces itself to be exactly 300px wide (disregarding the actual display width altogether), which is smaller than 352px for sure and would work on mobile devices. Are you sure some other CSS rule (or breakpoint) is not hiding the widget?
