### ISSUE TITLE
Redirecting to homepage

### ISSUE THREAD

**Issue by z33zain** [akshatmittal/youtube-realtime#23]
This script is totally useless. The coder is redirecting the new sites to his site.

**Comment by akshatmittal** [comment]
As you can see, the same is mentioned at the front of the repo as well as how to change it. For one, that's done because of the API requiment. The code will not work by default if you do not change the API Keys and the location URI.

**Comment by z33zain** [comment]
> As you can see, the same is mentioned at the front of the repo as well as how to change it. For one, that's done because of the API requiment. The code will not work by default if you do not change the API Keys and the location URI.

So how to do that? What steps need to do that?

**Comment by z33zain** [comment]
> As you can see, the same is mentioned at the front of the repo as well as how to change it. For one, that's done because of the API requiment. The code will not work by default if you do not change the API Keys and the location URI.

There is nothing so clear. There are so many JS files in the script and we don't know which piece of code to remove. And there is nothing in README file, nowhere is mentioned that how to change API's etc. Most people have customized the coding and removed the credits as well. But I was gonna promote you everywhere.

Please mention the steps to get this web app working.

**Comment by akshatmittal** [comment]
Check #14, and you just need to change the URL at the very top of `base.js`. Similarly, API Keys need to be changed in `keyManager.js`.

Anybody using this code without credits is violating the license. While I can handle some of those instances, it's really hard to tackle all of them. It's a common problem with open-source.

**Comment by z33zain** [comment]
Hello Akshat,

Which API do I need to get from YouTube API's. I am completely noob, SORRY! Mention the URL of APIs and steps.

Also edit the comments with #14  and link to this issue. 

Regards,
z33zain

**Comment by shanem2004** [comment]
you need to go into Google Cloud, create a project and "enable apis", then find YouTube API i think somnething like that.

**Comment by s1nnohlakes** [comment]
> Check #14, and you just need to change the URL at the very top of `base.js`. Similarly, API Keys need to be changed in `keyManager.js`.
> 
> Anybody using this code without credits is violating the license. While I can handle some of those instances, it's really hard to tackle all of them. It's a common problem with open-source.

After I change the URL at base.js, what do I put it in exactly?
