### ISSUE TITLE
Quota Limit in the API

### ISSUE THREAD

**Issue by ghost** [akshatmittal/youtube-realtime#24]
Youtube gives a quota of only 10,000 units/per day! It's getting used in a short span of time - How to get more quota? (Should we create a new project and generate another API Key) Please help me As soon as possible

**Comment by akshatmittal** [comment]
You need to request higher quota limit from your dashboard.

**Comment by ghost** [comment]
Okay! Thanks for it.By the way should we pay for extra quota request? Also I can see multiple keys in your keymanager.js file.Are all of those keys from the same project or different.Please help me in applying for extra quota (How Much Will I get as extra)?
