### ISSUE TITLE
Stopped Working and Showing Coder's name instead of channel names

### ISSUE THREAD

**Issue by z33zain** [akshatmittal/youtube-realtime#25]
Hello,

I am using this web app and it seems like you want us to purchase this app from you to get it proper functioning.

issue 1: stopped working even after updating 22 API keys in key manager. Not sure why there are 22 keys and what are these for. check it is not functioning

issue 2: showing your name everywhere. It should show channel's name instead of your name.

Thanks,

**Comment by akshatmittal** [comment]
Hey, please check the console before posting the issue here. YouTube Data API is not configured for the API Keys.

**Comment by z33zain** [comment]
So which keys are needed?

**Comment by akshatmittal** [comment]
> So which keys are needed?

Just enable the YouTube Data API in your project. You don't need multiple API keys.
