### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by OpenSourceSimon** [akshatmittal/youtube-realtime#35]
Is it possible to add an auto refresh? Because the subscriber count seems not updated.

**Comment by akshatmittal** [comment]
The count automatically refreshes. You may think it's not updating because YouTube has abbreviated the counts. https://twitter.com/iakshatmittal/status/1170691927030685696?

**Comment by StopmotionSimonYT** [comment]
No, i have 254 subs and if ik unsub is the count still 254
