### ISSUE TITLE
https://akshatmittal.com/youtube-realtime/#!/undefined

### ISSUE THREAD

**Issue by bundle-adjuster** [akshatmittal/youtube-realtime#36]
Hi Akshat, amazing project. Absolutely loved it.

However is it down right now? I tried to see a few of my channels on it, but it keeps reverting back to the subject I put this issue as. The website serving this is down? Or migrated completely? It is not able to pick up the YT channel. Please help resolve.

**Comment by akshatmittal** [comment]
The website is currently down. In fact both website are currently not working. I'm working on a fix, but no ETA yet,
