### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by petertenhoor** [akshatmittal/youtube-realtime#4]
Hi! I really like what you did with your youtube realtime counter project. It's nearly perfect!

I just noticed it doesn't work very well in Firefox. The channel name gets the value 'Loading..' and I can't get data from other channels unless I refresh.

Any idea why this is happening?

Greetings,

Peter

**Comment by akshatmittal** [comment]
Nice catch! Apparently Firefox is the only major browser to not support innerText.

Fixed the bug for Firefox with commit https://github.com/akshatmittal/youtube-realtime/commit/de85be84d0c125bb3f5761c681366fca1f4eb60c.

**Comment by petertenhoor** [comment]
Nice job, thank you!
