### ISSUE TITLE
Livesubcount.com

### ISSUE THREAD

**Issue by BillyJohnsonn** [akshatmittal/youtube-realtime#7]
Hey so when I was checking out your code I was checking out LiveSubCount.com's code out too, but they are leading to your site now... Why? I am guessing you told them to do that? I liked how there were two different Live Subscriber Count websites, what if some people don't like Livesubcount.com's style? Then they will go to your site. What if they don't like your sites syle? Then they will go to LiveSubCount.com. If you did make them go to your site, I think it would be better if there were two different ones. After all, yours is better than theirs. Theirs was just simple and friendly :) Just a thought. A lot of friends of mine were using both.

**Comment by akshatmittal** [comment]
An update will soon be coming with a new "Immersive" mode, which will be as clean as just a live counter. You'll love it!

**Comment by BillyJohnsonn** [comment]
So does that mean LiveSubCount.com will still be down?

**Comment by akshatmittal** [comment]
For the meantime, yes.

**Comment by BillyJohnsonn** [comment]
Hmm. Alright.

**Comment by akshatmittal** [comment]
I've implemented a very basic Immersive Mode just now. It's in beta though, works on most screens. A more complete version will be made soon as well.
