### ISSUE TITLE
Copyright Statement

### ISSUE THREAD

**Issue by 2mac** [akshatmittal/youtube-realtime#8]
You have a copyright statement at the bottom of `/index.html` which says that no one can reproduce this web app without permission, but you have released it under the GNU GPL.

Please change it to show the appropriate terms.

On a side note, with this being a web app, if you have all the rights to this program, I suggest changing to the GNU AGPLv3 which would make all other versions respect the users' freedom as well, and if anyone redeployed this app with changes, you could get them.

**Comment by akshatmittal** [comment]
Makes sense. I'll update it to GNU AGPLv3.

My intention with this open-source app was to allow people to make their own counters, with a link-back to my website or this repo. That apparently didn't happen and people just started making clones of this website, which made me add that statement in `/index.html`.
